### ISSUE TITLE
Icons (seemingly random) will not display

### ISSUE THREAD

**Issue by ExcelNet-Public** [emiliogrv/nativescript-vue-fonticon#1]
We have been using this plugin and love the readability it adds to our code and flexibility.  However, we have an odd issue where some icons display and some icons do not.  For example we have this code for test:

```
<StackLayout>
  <FontIcon name="fa-user" type="fas"/>
  <FontIcon name="fa-signal" type="fas"/>
  <Label class="fas" text="" />
</StackLayout>
```
The **Label** is using the glyph code for the fa-signal icon.  The first FontIcon tag works fine and the user symbol is displayed.  The second displays nothing, but the label for the same icon works just fine.  It is not limited to this icon, again it seems random some work, some do not.  Have set debug on import and all are getting imported. 

Not sure if this will help at all or not, but if I try to replace the glyph in the label with `&#xf012;` which seems to be strewn throughout the examples it will not display either.

We are using the latest version of Nativescript 5.3.3 and FontAwesome Pro fonts 5.8.1.  This is on an android emulator.

Any thoughts on getting this resolved would be great.  Thanks!

**Comment by emiliogrv** [comment]
Hello @ExcelNet-Public, Can you paste your own code where you import the fonts, CSS and JS?

Also I leave to you this link with some more info: https://github.com/NathanWalker/nativescript-fonticon#font-awesome-5

**Comment by jawa-the-hutt** [comment]
I just ran across this tonight on a project with `fa-star`.  It can be fixed by changing `FontIcon.vue` just a bit.  It has to do with the `width` property not reading the size prop correctly.  I fixed it like this:

```html
<template>
  <Label
    :class="type"
    :color="color"
    :fontSize="size"
    :text="name | fonticon"
    width="${size}"
    textAlignment="center"
    @tap="$emit('tap')"
  />
</template>
```

Not sure that's the best solution, but it appears to work.

To be clear, when using the built in `nativescript-fonticons` package, everything works fine with `fa-star`...it was just when adding in this package that the issue manifested.

**Comment by ExcelNet-Public** [comment]
Here is the import/instantiation code located in main.js:

```
import FontIcon from 'nativescript-vue-fonticon';
Vue.use(FontIcon, {
  debug: false,
  paths: {
    fa: '/fonts/fa5-all.min.css',
  },
});
```

Here is the CSS:

```
// FontAwesome 5 types for Vue Fonticon (nativescript-vue-fonticon)
.fa {
  font-family: "Font Awesome 5 Pro", fa-regular-400;
  font-weight: 400;
}
.fab {
  font-family: "Font Awesome 5 Brands", fa-brands-400;
  font-weight: 400;
}
.fal {
  font-family: "Font Awesome 5 Pro", fa-light-300;
  font-weight: 300;
}
.fas {
  font-family: "Font Awesome 5 Pro", fa-solid-900;
  font-weight: 900;
}
```

Here is one actual line of code that I can pass fa-user in as a prop and it works but fa-signal does not:

`<FontIcon :size="iconSize" :color="iconColor" :name="icon" :type="iconType"/>
`

All of the other attributes are props as well.  The only thing that changes from the working one to the non-working one is the name.  I have read the link referenced in the past and it did not help.

Thanks for the help!  I will probably try @jawa-the-hutt's suggested fix tomorrow and see what that does.

**Comment by ExcelNet-Public** [comment]
@jawa-the-hutt - This "fix" worked for me as well.  The icon is now displaying where it was previously not.

**Comment by emiliogrv** [comment]
@jawa-the-hutt I released a update with your suggestion.

Thank you both for your comments

**Comment by ExcelNet-Public** [comment]
Thanks!
