### ISSUE TITLE
Element <FontIcon> is undefined

### ISSUE THREAD

**Issue by prashantnirgun** [emiliogrv/nativescript-vue-fonticon#3]
Unknown custom element: <FontIcon> - did you register the component correctly? For recursive components, make sure to provide the "name" option. I am using following version
✔ Component nativescript has 5.4.2 version and is up to date.
✔ Component tns-core-modules has 5.4.3 version and is up to date.
✔ Component tns-android has 5.4.0 version and is up to date.

Steps involved in implementation
01 Installation `npm install nativescript-vue-fonticon --save`
02 download ttf and copied in /fonts [https://github.com/creationix/font-awesome](url)
03 download ttf and copied in /asets/css/font-awesome.css [https://github.com/creationix/font-awesome](url)
04 removed unwanted part from .css as shown in the video
05 Added code in main.js 
`import FontIcon from "nativescript-vue-fonticon";

import "./app.scss";

Vue.use(FontIcon, {
  componentName: "FIcon", // <-- Optional. Will be the name for component icon.
  debug: true, // <-- Optional. Will output the css mapping to console.
  paths: {
    fa: "./assets/css/font-awesome.css",
    ion: "./assets/css/ionicons.css"
  }
});`

06 No change in app.scss
`// NativeScript core theme
// @see https://docs.nativescript.org/ui/theme
@import "~nativescript-theme-core/scss/blue";
// Override variables here
@import "~nativescript-theme-core/scss/index";
// Global SCSS styling
// @see https://docs.nativescript.org/ui/styling
`
07 Component code is 
`<FontIcon name="fa-play" />`

Can you help me is implement is it because of new version i am using ?

Note : Eslint is showing Warning in import statement 
import FontIcon from "nativescript-vue-fonticon";

Could not find a declaration file for module 'nativescript-vue-fonticon'. '/home/prashant/www/drawer/node_modules/nativescript-vue-fonticon/src/index.js' implicitly has an 'any' type.
  Try `npm install @types/nativescript-vue-fonticon` if it exists or add a new declaration (.d.ts) file containing `declare module 'nativescript-vue-fonticon';`ts(7016)

**Comment by emiliogrv** [comment]
Hi @prashantnirgun try to deleting this line:

`componentName: "FIcon", // <-- Optional. Will be the name for component icon.`

It change the default name from `FontIcon` to `FIcon` that's the reason why Vue doesn't find `FontIcon` component
