### ISSUE TITLE
More info / Feature request

### ISSUE THREAD

**Issue by prashantnirgun** [emiliogrv/nativescript-vue-fonticon#4]
Is it possible to change the size or colour of the icon I found this https://github.com/FortAwesome/vue-fontawesome#why-use-the-concept-of-a-library can we do it in our example. If yes then please add it in readme.

If not then its a feature request

**Comment by emiliogrv** [comment]
Hi @prashantnirgun yes, we can change color and size, the readme has already that info here https://github.com/emiliogrv/nativescript-vue-fonticon#using
